# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--cpus", "2", "--memory", "2048"]
end
  config.vm.define "vanilla" do |vanilla|
    vanilla.vm.network "private_network", ip: "192.168.50.10"
    vanilla.vm.network "forwarded_port", guest: 8080, host: 8080
    vanilla.vm.network "forwarded_port", guest: 15672, host: 15672
    vanilla.vm.hostname = "vanilla.khome"
    vanilla.vm.box = "trusty64"
    vanilla.vm.box_url = "http://files.vagrantup.com/trusty64.box"
  end

  
  # -------- Enable provisioning with Ansible.  --------
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    # Uncomment below to see debug output.
    ansible.verbose = 'vvvv'
    ansible.groups = {
        "vanillaservers" => ["vanilla"]
    }
  end
end
